package com.trav.dao;

public class AgencyDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.agency_id
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private Integer agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.agency_name
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private String agencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.telephone
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.location
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.image_src
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private String imageSrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.agency_id
     *
     * @return the value of agency_info.agency_id
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public Integer getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.agency_id
     *
     * @param agencyId the value for agency_info.agency_id
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.agency_name
     *
     * @return the value of agency_info.agency_name
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public String getAgencyName() {
        return agencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.agency_name
     *
     * @param agencyName the value for agency_info.agency_name
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName == null ? null : agencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.telephone
     *
     * @return the value of agency_info.telephone
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.telephone
     *
     * @param telephone the value for agency_info.telephone
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.location
     *
     * @return the value of agency_info.location
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.location
     *
     * @param location the value for agency_info.location
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.image_src
     *
     * @return the value of agency_info.image_src
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public String getImageSrc() {
        return imageSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.image_src
     *
     * @param imageSrc the value for agency_info.image_src
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setImageSrc(String imageSrc) {
        this.imageSrc = imageSrc == null ? null : imageSrc.trim();
    }
}