package com.trav.dao;

import java.math.BigDecimal;

public class OrderManagementDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermanagement.id
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermanagement.username
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermanagement.dealerName
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    private String dealername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermanagement.review
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    private String review;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermanagement.totalCost
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    private BigDecimal totalcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermanagement.telephone
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermanagement.detail
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermanagement.id
     *
     * @return the value of ordermanagement.id
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermanagement.id
     *
     * @param id the value for ordermanagement.id
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermanagement.username
     *
     * @return the value of ordermanagement.username
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermanagement.username
     *
     * @param username the value for ordermanagement.username
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermanagement.dealerName
     *
     * @return the value of ordermanagement.dealerName
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public String getDealername() {
        return dealername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermanagement.dealerName
     *
     * @param dealername the value for ordermanagement.dealerName
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public void setDealername(String dealername) {
        this.dealername = dealername == null ? null : dealername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermanagement.review
     *
     * @return the value of ordermanagement.review
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public String getReview() {
        return review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermanagement.review
     *
     * @param review the value for ordermanagement.review
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public void setReview(String review) {
        this.review = review == null ? null : review.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermanagement.totalCost
     *
     * @return the value of ordermanagement.totalCost
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public BigDecimal getTotalcost() {
        return totalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermanagement.totalCost
     *
     * @param totalcost the value for ordermanagement.totalCost
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public void setTotalcost(BigDecimal totalcost) {
        this.totalcost = totalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermanagement.telephone
     *
     * @return the value of ordermanagement.telephone
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermanagement.telephone
     *
     * @param telephone the value for ordermanagement.telephone
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermanagement.detail
     *
     * @return the value of ordermanagement.detail
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermanagement.detail
     *
     * @param detail the value for ordermanagement.detail
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}