package com.trav.dao;

import java.math.BigDecimal;

public class PriceDetailDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_detail.price_id
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private Integer priceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_detail.transportation
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private BigDecimal transportation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_detail.accommodation
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private BigDecimal accommodation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_detail.dining
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private BigDecimal dining;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_detail.ticket
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private BigDecimal ticket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_detail.guidance_service
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private BigDecimal guidanceService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_detail.other
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    private BigDecimal other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_detail.price_id
     *
     * @return the value of price_detail.price_id
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public Integer getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_detail.price_id
     *
     * @param priceId the value for price_detail.price_id
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setPriceId(Integer priceId) {
        this.priceId = priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_detail.transportation
     *
     * @return the value of price_detail.transportation
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public BigDecimal getTransportation() {
        return transportation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_detail.transportation
     *
     * @param transportation the value for price_detail.transportation
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setTransportation(BigDecimal transportation) {
        this.transportation = transportation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_detail.accommodation
     *
     * @return the value of price_detail.accommodation
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public BigDecimal getAccommodation() {
        return accommodation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_detail.accommodation
     *
     * @param accommodation the value for price_detail.accommodation
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setAccommodation(BigDecimal accommodation) {
        this.accommodation = accommodation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_detail.dining
     *
     * @return the value of price_detail.dining
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public BigDecimal getDining() {
        return dining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_detail.dining
     *
     * @param dining the value for price_detail.dining
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setDining(BigDecimal dining) {
        this.dining = dining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_detail.ticket
     *
     * @return the value of price_detail.ticket
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public BigDecimal getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_detail.ticket
     *
     * @param ticket the value for price_detail.ticket
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setTicket(BigDecimal ticket) {
        this.ticket = ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_detail.guidance_service
     *
     * @return the value of price_detail.guidance_service
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public BigDecimal getGuidanceService() {
        return guidanceService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_detail.guidance_service
     *
     * @param guidanceService the value for price_detail.guidance_service
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setGuidanceService(BigDecimal guidanceService) {
        this.guidanceService = guidanceService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_detail.other
     *
     * @return the value of price_detail.other
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public BigDecimal getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_detail.other
     *
     * @param other the value for price_detail.other
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    public void setOther(BigDecimal other) {
        this.other = other;
    }
}