package com.trav.dao;

import java.math.BigDecimal;

public class RouteDO {

    private Integer routeId;


    private String routeTitle;


    private String imageSrc;


    private String cityName;


    private Integer duration;


    private String transportation;


    private BigDecimal price;


    private Integer priceDetailId;


    private String startDate;


    private String endDate;


    private Integer touristMin;


    private Integer touristMax;


    private Integer agencyId;


    private String detail;


    public Integer getRouteId() {
        return routeId;
    }


    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }


    public String getRouteTitle() {
        return routeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.route_title
     *
     * @param routeTitle the value for route_info.route_title
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setRouteTitle(String routeTitle) {
        this.routeTitle = routeTitle == null ? null : routeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.image_src
     *
     * @return the value of route_info.image_src
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public String getImageSrc() {
        return imageSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.image_src
     *
     * @param imageSrc the value for route_info.image_src
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setImageSrc(String imageSrc) {
        this.imageSrc = imageSrc == null ? null : imageSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.city_name
     *
     * @return the value of route_info.city_name
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.city_name
     *
     * @param cityName the value for route_info.city_name
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.duration
     *
     * @return the value of route_info.duration
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.duration
     *
     * @param duration the value for route_info.duration
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.transportation
     *
     * @return the value of route_info.transportation
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public String getTransportation() {
        return transportation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.transportation
     *
     * @param transportation the value for route_info.transportation
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setTransportation(String transportation) {
        this.transportation = transportation == null ? null : transportation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.price
     *
     * @return the value of route_info.price
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.price
     *
     * @param price the value for route_info.price
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.price_detail_id
     *
     * @return the value of route_info.price_detail_id
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public Integer getPriceDetailId() {
        return priceDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.price_detail_id
     *
     * @param priceDetailId the value for route_info.price_detail_id
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setPriceDetailId(Integer priceDetailId) {
        this.priceDetailId = priceDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.start_date
     *
     * @return the value of route_info.start_date
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.start_date
     *
     * @param startDate the value for route_info.start_date
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.end_date
     *
     * @return the value of route_info.end_date
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.end_date
     *
     * @param endDate the value for route_info.end_date
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.tourist_min
     *
     * @return the value of route_info.tourist_min
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public Integer getTouristMin() {
        return touristMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.tourist_min
     *
     * @param touristMin the value for route_info.tourist_min
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setTouristMin(Integer touristMin) {
        this.touristMin = touristMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.tourist_max
     *
     * @return the value of route_info.tourist_max
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public Integer getTouristMax() {
        return touristMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.tourist_max
     *
     * @param touristMax the value for route_info.tourist_max
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setTouristMax(Integer touristMax) {
        this.touristMax = touristMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.agency_id
     *
     * @return the value of route_info.agency_id
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public Integer getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.agency_id
     *
     * @param agencyId the value for route_info.agency_id
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.detail
     *
     * @return the value of route_info.detail
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.detail
     *
     * @param detail the value for route_info.detail
     *
     * @mbg.generated Fri Sep 04 16:25:22 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}