package com.travelia.mapper;

import com.travelia.entity.CityDO;

import java.util.List;

public interface CityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    int deleteByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    int insert(CityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    int insertSelective(CityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    CityDO selectByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    int updateByPrimaryKeySelective(CityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    int updateByPrimaryKey(CityDO record);


    List<CityDO> selectAllCities();
}