package com.travelia.mapper;

import com.travelia.entity.GroupOrderDOKey;

public interface GroupOrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_order
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int deleteByPrimaryKey(GroupOrderDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_order
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int insert(GroupOrderDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_order
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int insertSelective(GroupOrderDOKey record);
}