package com.travelia.mapper;

import com.travelia.entity.ItemCityDOKey;

public interface ItemCityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_city
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int deleteByPrimaryKey(ItemCityDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_city
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int insert(ItemCityDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_city
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int insertSelective(ItemCityDOKey record);
}