package com.travelia.mapper;

import com.travelia.entity.ItemImageDO;

public interface ItemImageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_image
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int deleteByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_image
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int insert(ItemImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_image
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int insertSelective(ItemImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_image
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    ItemImageDO selectByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_image
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int updateByPrimaryKeySelective(ItemImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_image
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    int updateByPrimaryKey(ItemImageDO record);
}