package com.travelia.mapper;

import com.travelia.entity.ItemDO;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    ItemDO selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    int updateByPrimaryKey(ItemDO record);


    List<ItemDO> selectAllItems();


    List<ItemDO> selectByAgencyId(Integer agencyId);

    List<ItemDO> selectAllByOrderTimesDESC();


    List<ItemDO> selectAllByCreateDateDESC();
}