package com.travelia.mapper;

import com.travelia.entity.ItemDO;
import com.travelia.entity.OrderDO;

import java.util.List;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Sep 12 17:27:34 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Sep 12 17:27:34 GMT+08:00 2020
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Sep 12 17:27:34 GMT+08:00 2020
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Sep 12 17:27:34 GMT+08:00 2020
     */
    OrderDO selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Sep 12 17:27:34 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Sep 12 17:27:34 GMT+08:00 2020
     */
    int updateByPrimaryKey(OrderDO record);


    List<OrderDO> selectAllOrders();


    List<OrderDO> selectByAgencyId(Integer agencyId);

//    List<ItemDO> selectAllByOrderTimesDESC();
//
//
//    List<ItemDO> selectAllByCreateDateDESC();
}