package com.trav.mapper;

import com.trav.dao.AgencyDO;

public interface AgencyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int deleteByPrimaryKey(Integer agencyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int insert(AgencyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int insertSelective(AgencyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    AgencyDO selectByPrimaryKey(Integer agencyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int updateByPrimaryKeySelective(AgencyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agency_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int updateByPrimaryKey(AgencyDO record);
}