package com.trav.mapper;

import com.trav.dao.OrderManagementDO;

public interface OrderManagementDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermanagement
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermanagement
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    int insert(OrderManagementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermanagement
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    int insertSelective(OrderManagementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermanagement
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    OrderManagementDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermanagement
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    int updateByPrimaryKeySelective(OrderManagementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermanagement
     *
     * @mbg.generated Fri Sep 04 08:52:24 CST 2020
     */
    int updateByPrimaryKey(OrderManagementDO record);
}