package com.trav.mapper;

import com.trav.dao.RouteDO;

public interface RouteDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int deleteByPrimaryKey(Integer routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int insert(RouteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int insertSelective(RouteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    RouteDO selectByPrimaryKey(Integer routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int updateByPrimaryKeySelective(RouteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated Fri Sep 04 15:58:49 CST 2020
     */
    int updateByPrimaryKey(RouteDO record);
}