package com.travelia.entity;

public class AdminDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.admin_id
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.admin_name
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.admin_account
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    private String adminAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.encrypt_password
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    private String encryptPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.admin_id
     *
     * @return the value of admin_info.admin_id
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.admin_id
     *
     * @param adminId the value for admin_info.admin_id
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.admin_name
     *
     * @return the value of admin_info.admin_name
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.admin_name
     *
     * @param adminName the value for admin_info.admin_name
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.admin_account
     *
     * @return the value of admin_info.admin_account
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    public String getAdminAccount() {
        return adminAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.admin_account
     *
     * @param adminAccount the value for admin_info.admin_account
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    public void setAdminAccount(String adminAccount) {
        this.adminAccount = adminAccount == null ? null : adminAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.encrypt_password
     *
     * @return the value of admin_info.encrypt_password
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    public String getEncryptPassword() {
        return encryptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.encrypt_password
     *
     * @param encryptPassword the value for admin_info.encrypt_password
     *
     * @mbg.generated Wed Sep 09 09:04:12 CST 2020
     */
    public void setEncryptPassword(String encryptPassword) {
        this.encryptPassword = encryptPassword == null ? null : encryptPassword.trim();
    }
}