package com.travelia.entity;

public class AgencyDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.agency_id
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private Integer agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.agency_account
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String agencyAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.encrypt_password
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String encryptPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.agency_title
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String agencyTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.agency_image_source
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String agencyImageSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.agency_telephone
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String agencyTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.agency_address
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String agencyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agency_info.agency_email
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String agencyEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.agency_id
     *
     * @return the value of agency_info.agency_id
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public Integer getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.agency_id
     *
     * @param agencyId the value for agency_info.agency_id
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.agency_account
     *
     * @return the value of agency_info.agency_account
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getAgencyAccount() {
        return agencyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.agency_account
     *
     * @param agencyAccount the value for agency_info.agency_account
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setAgencyAccount(String agencyAccount) {
        this.agencyAccount = agencyAccount == null ? null : agencyAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.encrypt_password
     *
     * @return the value of agency_info.encrypt_password
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getEncryptPassword() {
        return encryptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.encrypt_password
     *
     * @param encryptPassword the value for agency_info.encrypt_password
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setEncryptPassword(String encryptPassword) {
        this.encryptPassword = encryptPassword == null ? null : encryptPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.agency_title
     *
     * @return the value of agency_info.agency_title
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getAgencyTitle() {
        return agencyTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.agency_title
     *
     * @param agencyTitle the value for agency_info.agency_title
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setAgencyTitle(String agencyTitle) {
        this.agencyTitle = agencyTitle == null ? null : agencyTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.agency_image_source
     *
     * @return the value of agency_info.agency_image_source
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getAgencyImageSource() {
        return agencyImageSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.agency_image_source
     *
     * @param agencyImageSource the value for agency_info.agency_image_source
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setAgencyImageSource(String agencyImageSource) {
        this.agencyImageSource = agencyImageSource == null ? null : agencyImageSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.agency_telephone
     *
     * @return the value of agency_info.agency_telephone
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getAgencyTelephone() {
        return agencyTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.agency_telephone
     *
     * @param agencyTelephone the value for agency_info.agency_telephone
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setAgencyTelephone(String agencyTelephone) {
        this.agencyTelephone = agencyTelephone == null ? null : agencyTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.agency_address
     *
     * @return the value of agency_info.agency_address
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getAgencyAddress() {
        return agencyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.agency_address
     *
     * @param agencyAddress the value for agency_info.agency_address
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setAgencyAddress(String agencyAddress) {
        this.agencyAddress = agencyAddress == null ? null : agencyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agency_info.agency_email
     *
     * @return the value of agency_info.agency_email
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getAgencyEmail() {
        return agencyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agency_info.agency_email
     *
     * @param agencyEmail the value for agency_info.agency_email
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setAgencyEmail(String agencyEmail) {
        this.agencyEmail = agencyEmail == null ? null : agencyEmail.trim();
    }
}