package com.travelia.entity;

public class CityDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_info.city_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_info.city_name
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_info.image_src
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private String imageSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_info.country
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private String country;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_info.city_id
     *
     * @return the value of city_info.city_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_info.city_id
     *
     * @param cityId the value for city_info.city_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_info.city_name
     *
     * @return the value of city_info.city_name
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_info.city_name
     *
     * @param cityName the value for city_info.city_name
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_info.image_src
     *
     * @return the value of city_info.image_src
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public String getImageSrc() {
        return imageSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_info.image_src
     *
     * @param imageSrc the value for city_info.image_src
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setImageSrc(String imageSrc) {
        this.imageSrc = imageSrc == null ? null : imageSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_info.country
     *
     * @return the value of city_info.country
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_info.country
     *
     * @param country the value for city_info.country
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }
}