package com.travelia.entity;

public class CityDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_info.city_id
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_info.city_name
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_info.is_domestic
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private Integer isDomestic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_info.city_image_source
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String cityImageSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_info.city_id
     *
     * @return the value of city_info.city_id
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_info.city_id
     *
     * @param cityId the value for city_info.city_id
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_info.city_name
     *
     * @return the value of city_info.city_name
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_info.city_name
     *
     * @param cityName the value for city_info.city_name
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_info.is_domestic
     *
     * @return the value of city_info.is_domestic
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public Integer getIsDomestic() {
        return isDomestic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_info.is_domestic
     *
     * @param isDomestic the value for city_info.is_domestic
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setIsDomestic(Integer isDomestic) {
        this.isDomestic = isDomestic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_info.city_image_source
     *
     * @return the value of city_info.city_image_source
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getCityImageSource() {
        return cityImageSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_info.city_image_source
     *
     * @param cityImageSource the value for city_info.city_image_source
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setCityImageSource(String cityImageSource) {
        this.cityImageSource = cityImageSource == null ? null : cityImageSource.trim();
    }
}