package com.travelia.entity;

public class GroupOrderDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_order.group_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_order.order_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_order.group_id
     *
     * @return the value of group_order.group_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_order.group_id
     *
     * @param groupId the value for group_order.group_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_order.order_id
     *
     * @return the value of group_order.order_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_order.order_id
     *
     * @param orderId the value for group_order.order_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}