package com.travelia.entity;

public class GroupDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.group_id
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.group_current_travelers
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private Integer groupCurrentTravelers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.group_create_date
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String groupCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.group_end_date
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private String groupEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.group_status
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    private Integer groupStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.group_id
     *
     * @return the value of group_info.group_id
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.group_id
     *
     * @param groupId the value for group_info.group_id
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.group_current_travelers
     *
     * @return the value of group_info.group_current_travelers
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public Integer getGroupCurrentTravelers() {
        return groupCurrentTravelers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.group_current_travelers
     *
     * @param groupCurrentTravelers the value for group_info.group_current_travelers
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setGroupCurrentTravelers(Integer groupCurrentTravelers) {
        this.groupCurrentTravelers = groupCurrentTravelers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.group_create_date
     *
     * @return the value of group_info.group_create_date
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getGroupCreateDate() {
        return groupCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.group_create_date
     *
     * @param groupCreateDate the value for group_info.group_create_date
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setGroupCreateDate(String groupCreateDate) {
        this.groupCreateDate = groupCreateDate == null ? null : groupCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.group_end_date
     *
     * @return the value of group_info.group_end_date
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public String getGroupEndDate() {
        return groupEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.group_end_date
     *
     * @param groupEndDate the value for group_info.group_end_date
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setGroupEndDate(String groupEndDate) {
        this.groupEndDate = groupEndDate == null ? null : groupEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.group_status
     *
     * @return the value of group_info.group_status
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public Integer getGroupStatus() {
        return groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.group_status
     *
     * @param groupStatus the value for group_info.group_status
     *
     * @mbg.generated Wed Sep 09 09:49:03 CST 2020
     */
    public void setGroupStatus(Integer groupStatus) {
        this.groupStatus = groupStatus;
    }
}