package com.travelia.entity;

public class ItemCityDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_city.item_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_city.city_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private Integer cityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_city.item_id
     *
     * @return the value of item_city.item_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_city.item_id
     *
     * @param itemId the value for item_city.item_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_city.city_id
     *
     * @return the value of item_city.city_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_city.city_id
     *
     * @param cityId the value for item_city.city_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
}