package com.travelia.entity;

public class ItemImageDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_image.image_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private Integer imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_image.item_image_source
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private String itemImageSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_image.item_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_image.image_id
     *
     * @return the value of item_image.image_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_image.image_id
     *
     * @param imageId the value for item_image.image_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_image.item_image_source
     *
     * @return the value of item_image.item_image_source
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public String getItemImageSource() {
        return itemImageSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_image.item_image_source
     *
     * @param itemImageSource the value for item_image.item_image_source
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setItemImageSource(String itemImageSource) {
        this.itemImageSource = itemImageSource == null ? null : itemImageSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_image.item_id
     *
     * @return the value of item_image.item_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_image.item_id
     *
     * @param itemId the value for item_image.item_id
     *
     * @mbg.generated Tue Sep 08 10:22:17 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}